"""Core utilities, configuration, and base abstractions for market_intel."""

from market_intel.core.cache import (
    CACHE_HITS_TOTAL,
    CACHE_MISSES_TOTAL,
    DeduplicationCache,
    generate_fingerprint,
    normalize_url,
)
from market_intel.core.config import Settings, get_settings
from market_intel.core.exceptions import (
    AuthenticationError,
    CacheError,
    ConfigurationError,
    DatabaseError,
    ExtractorError,
    MarketIntelError,
    NewsAPIError,
    RateLimitError,
)
from market_intel.core.logger import configure_logging, get_logger
from market_intel.core.schemas import (
    ArticleSchema,
    DocumentEnrichmentResult,
    EmbeddingResult,
    EnrichedSignalSchema,
    EntityItem,
    FilingSchema,
    FinancialMetricsSchema,
    FundamentalsSchema,
    NERResult,
    NewsAPIResponseSchema,
    PostSchema,
    PriceSchema,
    SentimentResult,
    SourceSchema,
    SummaryResult,
)

__all__ = [
    "Settings",
    "get_settings",
    "MarketIntelError",
    "ConfigurationError",
    "ExtractorError",
    "RateLimitError",
    "AuthenticationError",
    "NewsAPIError",
    "DatabaseError",
    "CacheError",
    "DeduplicationCache",
    "generate_fingerprint",
    "normalize_url",
    "CACHE_HITS_TOTAL",
    "CACHE_MISSES_TOTAL",
    "configure_logging",
    "get_logger",
    "SourceSchema",
    "ArticleSchema",
    "NewsAPIResponseSchema",
    "FinancialMetricsSchema",
    "FilingSchema",
    "PostSchema",
    "PriceSchema",
    "FundamentalsSchema",
    "EnrichedSignalSchema",
    "SentimentResult",
    "EntityItem",
    "NERResult",
    "SummaryResult",
    "EmbeddingResult",
    "DocumentEnrichmentResult",
]
